name: Build and Deploy 🕛
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE: ${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.3.1

      - name: Pnpm 🧱
        uses: pnpm/action-setup@v4.2.0

      - name: Node.js ⚓
        uses: actions/setup-node@v4.4.0
        with:
          node-version: latest
          cache: pnpm

      - name: Install && Build 🔧
        run: |
          pnpm i --frozen-lockfile
          pnpm build
          touch dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        if: github.ref_name == 'main'
        with:
          folder: dist
